#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

// ! HTTP STATUS CODES - 2xx Success
#define HTTP_OK 200
#define HTTP_CREATED 201

// ! HTTP STATUS CODES - 3xx Redirect
#define HTTP_MOVED_PERMANENTLY 301

// ! HTTP STATUS CODES - 4xx Client Error
#define HTTP_BAD_REQUEST 400
#define HTTP_FORBIDDEN 403
#define HTTP_NOT_FOUND 404
#define HTTP_METHOD_NOT_ALLOWED 405
#define HTTP_LENGTH_REQUIRED 411
#define HTTP_PAYLOAD_TOO_LARGE 413
#define HTTP_URI_TOO_LONG 414
#define HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE 431

// ! HTTP STATUS CODES - 5xx Server Error
#define HTTP_INTERNAL_SERVER_ERROR 500
#define HTTP_NOT_IMPLEMENTED 501
#define HTTP_GATEWAY_TIMEOUT 504
#define HTTP_VERSION_NOT_SUPPORTED 505

// ! HTTP HEADER NAMES
#define HEADER_CONTENT_TYPE "Content-Type"
#define HEADER_CONTENT_LENGTH "Content-Length"
#define HEADER_CONTENT_DISPOSITION "Content-Disposition"
#define HEADER_HOST "host"
#define HEADER_COOKIE "cookie"

// ! HTTP METHODS
#define METHOD_GET "GET"
#define METHOD_POST "POST"
#define METHOD_DELETE "DELETE"
#define METHOD_PUT "PUT"
#define METHOD_PATCH "PATCH"
#define METHOD_HEAD "HEAD"
#define METHOD_OPTIONS "OPTIONS"

// ! HTTP VERSIONS
#define HTTP_VERSION_1_0 "HTTP/1.0"
#define HTTP_VERSION_1_1 "HTTP/1.1"

// ! DELIMITERS
#define CRLF "\r\n"
#define DOUBLE_CRLF "\r\n\r\n"
#define COLON ':'
#define SEMICOLON ';'
#define EQUALS '='
#define HASH '#'
#define QUESTION '?'
#define DOT '.'
#define SLASH '/'

// ! MAX LIMITS
#define MAX_URI_LENGTH 8192
#define MAX_HEADER_SIZE 8192
#define BUFFER_SIZE 4096

// ! TIMEOUTS
#define CLIENT_TIMEOUT 60
#define CGI_TIMEOUT 10

// ! DEFAULTS
#define DEFAULT_PORT 80
#define DIR_PERMISSIONS 0755
#define INVALID_FD -1

// ! CGI
#define CGI_INTERFACE "CGI/1.1"
#define SERVER_PROTOCOL "HTTP/1.1"

// ! GUID
#define GUID_LENGTH 36
#define GUID_CHARSET "0123456789AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz"

// ! SESSION
#define SESSION_COOKIE_NAME "webserv_sid"
#define SESSION_ID_LENGTH 32
#define SESSION_TIMEOUT 1800
#define SESSION_CLEANUP_INTERVAL 60

#endif