#ifndef ENUM_HPP
#define ENUM_HPP
enum Type { TOKEN_WORD, TOKEN_STRING, TOKEN_SEMICOLON, TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_EOF };
enum FileType { SINGLEFILE, DIRECTORY, UNKNOWN };
enum HandlerType { STATIC, DIRECTORY_LISTING, CGI, UPLOAD, ERROR_PAGE, NOT_FOUND, DELETE_FILE };

#endif